import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import SideBar from "@/components/nevigation/SideBar";
import MobileBar from "@/components/nevigation/MobileBar";
import NevBar from "@/components/nevigation/NevBar";

const roboto = Inter({
  weight: "400",
  subsets: ["greek-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${roboto.className} bg-black text-white `}>
          <NevBar />
          <div className=" flex ">
            <SideBar />
            <MobileBar />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
